## **Libraries**

In [ ]:
import pandas as pd
import numpy as np

## **Data collection**

In [ ]:
customer_df = pd.read_csv('data/raw/olist_customers_dataset.csv')
geolocation_df = pd.read_csv('data/raw/olist_geolocation_dataset.csv')
order_items_df = pd.read_csv('data/raw/olist_order_items_dataset.csv')
order_payments_df = pd.read_csv('data/raw/olist_order_payments_dataset.csv')
order_reviews_df = pd.read_csv('data/raw/input/olist_order_reviews_dataset.csv')
orders_df = pd.read_csv('data/raw/olist_orders_dataset.csv')
products_df = pd.read_csv('data/raw/olist_products_dataset.csv')
sellers_df = pd.read_csv('data/raw/olist_sellers_dataset.csv')

## **Data Exploratory**

In [ ]:
# A list is created with the names of the variables
datasets = ["customer_df", "geolocation_df", "order_items_df", "order_payments_df",
            "order_reviews_df", "orders_df", "products_df", "sellers_df"]

# A function is created to obtain the information of each dataset
def getInfoDataset(df):
  return {
      "dataset": df.name,
      "n_rows": df.shape[0],
      "n_cols": df.shape[1],
      "null_amount": df.isnull().sum().sum(),
      "q_null_columns": df.isnull().sum(axis=0).gt(0).sum(),
      "null_columns": ", ".join(df.columns[df.isnull().sum(axis=0).gt(0)].tolist()),
  }

# The information of each dataset is obtained and a list of dictionaries is created
info_datasets = []
for dataset in datasets:
  df = globals()[dataset]
  df.name = dataset
  info_datasets.append(getInfoDataset(df))

# A DataFrame is created from the list of dictionaries
info_datasets_df = pd.DataFrame(info_datasets)
info_datasets_df.style.set_table_styles([{"selector": "th", "props": [("text-align", "center"), ("font-weight", "bold")]}])

In [ ]:
# Define an empty list to store the table data
table_data = []

# Iterate through each dataset
for dataset_name in datasets:
    data = eval(dataset_name)

    # Get column information for the current dataset
    for col in data.columns:
        # Count null values and calculate null percentage
        null_count = data[col].isnull().sum()
        null_perc = round((null_count / len(data)) * 100, 4)

        # Get data type and number of unique entries (categorical count)
        data_type = data[col].dtype
        categorical_count = data[col].nunique()

        # Append data for the current column to the table_data list
        table_data.append({
            "dataset_name": dataset_name,
            "columns_name": col,
            "nulls": null_count,
            "nulls_percentage": str(null_perc) + "%",
            "data_type": data_type,
            "total_categorical": categorical_count
        })

# Create the pandas DataFrame from the table_data list
df = pd.DataFrame(table_data)
df

,dataset_name,columns_name,nulls,nulls_percentage,data_type,total_categorical
0,customer_df,customer_id,0,0.0%,object,99441
1,customer_df,customer_unique_id,0,0.0%,object,96096
2,customer_df,customer_zip_code_prefix,0,0.0%,int64,14994
3,customer_df,customer_city,0,0.0%,object,4119
4,customer_df,customer_state,0,0.0%,object,27
5,geolocation_df,geolocation_zip_code_prefix,0,0.0%,int64,19015
6,geolocation_df,geolocation_lat,0,0.0%,float64,717360
7,geolocation_df,geolocation_lng,0,0.0%,float64,717613
8,geolocation_df,geolocation_city,0,0.0%,object,8011
9,geolocation_df,geolocation_state,0,0.0%,object,27
10,order_items_df,order_id,0,0.0%,object,98666
11,order_items_df,order_item_id,0,0.0%,int64,21
12,order_items_df,product_id,0,0.0%,object,32951
13,order_items_df,seller_id,0,0.0%,object,3095
14,order_items_df,shipping_limit_date,0,0.0%,object,93318
15,order_items_df,price,0,0.0%,float64,5968
16,order_items_df,freight_value,0,0.0%,float64,6999
17,order_payments_df,order_id,0,0.0%,object,99440
18,order_payments_df,payment_sequential,0,0.0%,int64,29
19,order_payments_df,payment_type,0,0.0%,object,5
20,order_payments_df,payment_installments,0,0.0%,int64,24
21,order_payments_df,payment_value,0,0.0%,float64,29077
22,order_reviews_df,review_id,0,0.0%,object,98410
23,order_reviews_df,order_id,0,0.0%,object,98673
24,order_reviews_df,review_score,0,0.0%,int64,5
25,order_reviews_df,review_comment_title,87656,88.3415%,object,4527
26,order_reviews_df,review_comment_message,58247,58.7025%,object,36159
27,order_reviews_df,review_creation_date,0,0.0%,object,636
28,order_reviews_df,review_answer_timestamp,0,0.0%,object,98248
29,orders_df,order_id,0,0.0%,object,99441
30,orders_df,customer_id,0,0.0%,object,99441
31,orders_df,order_status,0,0.0%,object,8
32,orders_df,order_purchase_timestamp,0,0.0%,object,98875
33,orders_df,order_approved_at,160,0.1609%,object,90733
34,orders_df,order_delivered_carrier_date,1783,1.793%,object,81018
35,orders_df,order_delivered_customer_date,2965,2.9817%,object,95664
36,orders_df,order_estimated_delivery_date,0,0.0%,object,459
37,products_df,product_id,0,0.0%,object,32951
38,products_df,product_category_name,610,1.8512%,object,73
39,products_df,product_name_lenght,610,1.8512%,float64,66
40,products_df,product_description_lenght,610,1.8512%,float64,2960
41,products_df,product_photos_qty,610,1.8512%,float64,19
42,products_df,product_weight_g,2,0.0061%,float64,2204
43,products_df,product_length_cm,2,0.0061%,float64,99
44,products_df,product_height_cm,2,0.0061%,float64,102
45,products_df,product_width_cm,2,0.0061%,float64,95
46,sellers_df,seller_id,0,0.0%,object,3095
47,sellers_df,seller_zip_code_prefix,0,0.0%,int64,2246
48,sellers_df,seller_city,0,0.0%,object,611
49,sellers_df,seller_state,0,0.0%,object,23

## **Data preprocessing (Feature Enginering)**

* order_reviews_df

In [ ]:
# We remove the 'review_comment_title' column
order_reviews_df.drop('review_comment_title', axis=1, inplace=True)
# We replace the NaN values of 'review_comment_message' with 'Unspecified'
order_reviews_df['review_comment_message'].fillna("Unspecified", inplace=True)
# Modified 'review_creation_date' in datetime
order_reviews_df['review_creation_date'] = pd.to_datetime(order_reviews_df['review_creation_date'])
# Modified 'review_answer_timestamp' in datetime
order_reviews_df['review_answer_timestamp'] = pd.to_datetime(order_reviews_df['review_answer_timestamp'])
# Survey response time in hours
order_reviews_df['answer_hour'] = order_reviews_df['review_answer_timestamp'].dt.hour
# Modified 'review_creation_date' in datetime
order_reviews_df['review_creation_date'] = pd.to_datetime(order_reviews_df['review_creation_date'])
# Survey response time in days
order_reviews_df['day_of_month'] = order_reviews_df['review_creation_date'].dt.day
order_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_message   99224 non-null  object
 4   review_creation_date     99224 non-null  datetime64[ns]
 5   review_answer_timestamp  99224 non-null  datetime64[ns]
 6   answer_hour              99224 non-null  int32
 7   day_of_month             99224 non-null  int32
dtypes: datetime64[ns](2), int32(2), int64(1), object(3)
memory usage: 5.3+ MB

* products_df

In [ ]:
# We eliminate the rows that contain NaN in 'products'
products_df.dropna(axis=0, inplace=True)
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32340 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32340 non-null  object
 1   product_category_name       32340 non-null  object
 2   product_name_lenght         32340 non-null  float64
 3   product_description_lenght  32340 non-null  float64
 4   product_photos_qty          32340 non-null  float64
 5   product_weight_g            32340 non-null  float64
 6   product_length_cm           32340 non-null  float64
 7   product_height_cm           32340 non-null  float64
 8   product_width_cm            32340 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.5+ MB

* orders_df

In [ ]:
# We use the fill() method to replace NULL values with the value of the previous row
orders_df['order_delivered_customer_date'] = orders_df['order_delivered_customer_date'].fillna(method='ffill')
# Modified 'order_purchase_timestamp' in datetime
orders_df['datetime'] =  pd.to_datetime(orders_df['order_purchase_timestamp'])
# Rows with missing NaN values are deleted
orders_df.dropna(axis=0, inplace=True)

In [ ]:
# We create two columns separating only the dates.
orders_df['delivered_time'] = pd.to_datetime(orders_df['order_delivered_customer_date'].str[:10], format='%Y-%m-%d').dt.date
orders_df['estimated_time'] = pd.to_datetime(orders_df['order_estimated_delivery_date'].str[:10], format='%Y-%m-%d').dt.date

In [ ]:
# We create a new column with the difference in days of 'estimated time' and 'delivered time'.
orders_df['diff_days'] = orders_df['delivered_time'] - orders_df['estimated_time']
orders_df['diff_days'] = pd.to_timedelta(orders_df['diff_days'])
orders_df['diff_days'] = orders_df['diff_days'].dt.days

In [ ]:
# We create a new column with the number of weeks spent per year.
orders_df['weekly'] = pd.to_datetime(orders_df['order_delivered_customer_date']).dt.isocalendar().week

In [ ]:
# We create a new column with the year and month of 'order_delivered_customer_date'.
orders_df['yearly'] = pd.to_datetime(orders_df['order_delivered_customer_date']).dt.to_period('M')
orders_df['yearly'] = orders_df['yearly'].astype(str)

In [ ]:
# Convert an 'object' to an object of type 'datetime'.
orders_df["order_purchase_timestamp"] = pd.to_datetime(orders_df["order_purchase_timestamp"])

In [ ]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97644 entries, 0 to 99440
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       97644 non-null  object
 1   customer_id                    97644 non-null  object
 2   order_status                   97644 non-null  object
 3   order_purchase_timestamp       97644 non-null  datetime64[ns]
 4   order_approved_at              97644 non-null  object
 5   order_delivered_carrier_date   97644 non-null  object
 6   order_delivered_customer_date  97644 non-null  object
 7   order_estimated_delivery_date  97644 non-null  object
 8   datetime                       97644 non-null  datetime64[ns]
 9   delivered_time                 97644 non-null  object
 10  estimated_time                 97644 non-null  object
 11  diff_days                      97644 non-null  int64
 12  weekly                         97644 non-null  UInt32
 13  yearly                         97644 non-null  object
dtypes: UInt32(1), datetime64[ns](2), int64(1), object(10)
memory usage: 10.9+ MB

* order_payments_df

In [ ]:
# A new column is created in the order payments dataset called 'value_log' that contains the logarithm values of the payment value.
order_payments_df['value_log'] = order_payments_df['payment_value'].apply(lambda x: np.log(x) if x > 0 else 0)

* sellers_df

In [ ]:
# We add a new column that contains only 10 digits of seller_id
sellers_df['seller_id_small'] = sellers_df['seller_id'].str[-10:]

* **Merging Datasets**

In [ ]:
total_orders_df = orders_df.merge(order_items_df, on='order_id', how='inner')

In [ ]:
product_orders_df = total_orders_df.merge(products_df, on='product_id', how='inner')

In [ ]:
seller_products_df = product_orders_df.merge(sellers_df, on='seller_id', how='inner')

In [ ]:
payments_df = seller_products_df.merge(order_payments_df, on='order_id', how='inner')

In [ ]:
customer_order_df = payments_df.merge(customer_df, on='customer_id', how='inner')

In [ ]:
olist_df = customer_order_df.merge(order_reviews_df, on='order_id', how='inner')

In [ ]:
olist_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114422 entries, 0 to 114421
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       114422 non-null  object
 1   customer_id                    114422 non-null  object
 2   order_status                   114422 non-null  object
 3   order_purchase_timestamp       114422 non-null  datetime64[ns]
 4   order_approved_at              114422 non-null  object
 5   order_delivered_carrier_date   114422 non-null  object
 6   order_delivered_customer_date  114422 non-null  object
 7   order_estimated_delivery_date  114422 non-null  object
 8   datetime                       114422 non-null  datetime64[ns]
 9   delivered_time                 114422 non-null  object
 10  estimated_time                 114422 non-null  object
 11  diff_days                      114422 non-null  int64
 12  weekly                         114422 non-null  UInt32
 13  yearly                         114422 non-null  object
 14  order_item_id                  114422 non-null  int64
 15  product_id                     114422 non-null  object
 16  seller_id                      114422 non-null  object
 17  shipping_limit_date            114422 non-null  object
 18  price                          114422 non-null  float64
 19  freight_value                  114422 non-null  float64
 20  product_category_name          114422 non-null  object
 21  product_name_lenght            114422 non-null  float64
 22  product_description_lenght     114422 non-null  float64
 23  product_photos_qty             114422 non-null  float64
 24  product_weight_g               114422 non-null  float64
 25  product_length_cm              114422 non-null  float64
 26  product_height_cm              114422 non-null  float64
 27  product_width_cm               114422 non-null  float64
 28  seller_zip_code_prefix         114422 non-null  int64
 29  seller_city                    114422 non-null  object
 30  seller_state                   114422 non-null  object
 31  seller_id_small                114422 non-null  object
 32  payment_sequential             114422 non-null  int64
 33  payment_type                   114422 non-null  object
 34  payment_installments           114422 non-null  int64
 35  payment_value                  114422 non-null  float64
 36  value_log                      114422 non-null  float64
 37  customer_unique_id             114422 non-null  object
 38  customer_zip_code_prefix       114422 non-null  int64
 39  customer_city                  114422 non-null  object
 40  customer_state                 114422 non-null  object
 41  review_id                      114422 non-null  object
 42  review_score                   114422 non-null  int64
 43  review_comment_message         114422 non-null  object
 44  review_creation_date           114422 non-null  datetime64[ns]
 45  review_answer_timestamp        114422 non-null  datetime64[ns]
 46  answer_hour                    114422 non-null  int32
 47  day_of_month                   114422 non-null  int32
dtypes: UInt32(1), datetime64[ns](4), float64(11), int32(2), int64(7), object(23)
memory usage: 40.7+ MB

In [ ]:
# List of column names that won't be required
columns_to_delete = ['customer_id', 'order_status', 'order_approved_at',
                       'order_delivered_carrier_date', 'order_delivered_customer_date',
                       'order_estimated_delivery_date', 'delivered_time', 'estimated_time',
                       'yearly', 'order_item_id', 'shipping_limit_date', 'product_name_lenght',
                       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
                       'product_length_cm', 'product_height_cm', 'product_width_cm',
                       'customer_state', 'review_id', 'review_comment_message',
                       'review_answer_timestamp']
# Delete the specified columns
olist_df = olist_df.drop(columns_to_delete, axis=1)

In [ ]:
olist_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114422 entries, 0 to 114421
Data columns (total 26 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  114422 non-null  object
 1   order_purchase_timestamp  114422 non-null  datetime64[ns]
 2   datetime                  114422 non-null  datetime64[ns]
 3   diff_days                 114422 non-null  int64
 4   weekly                    114422 non-null  UInt32
 5   product_id                114422 non-null  object
 6   seller_id                 114422 non-null  object
 7   price                     114422 non-null  float64
 8   freight_value             114422 non-null  float64
 9   product_category_name     114422 non-null  object
 10  seller_zip_code_prefix    114422 non-null  int64
 11  seller_city               114422 non-null  object
 12  seller_state              114422 non-null  object
 13  seller_id_small           114422 non-null  object
 14  payment_sequential        114422 non-null  int64
 15  payment_type              114422 non-null  object
 16  payment_installments      114422 non-null  int64
 17  payment_value             114422 non-null  float64
 18  value_log                 114422 non-null  float64
 19  customer_unique_id        114422 non-null  object
 20  customer_zip_code_prefix  114422 non-null  int64
 21  customer_city             114422 non-null  object
 22  review_score              114422 non-null  int64
 23  review_creation_date      114422 non-null  datetime64[ns]
 24  answer_hour               114422 non-null  int32
 25  day_of_month              114422 non-null  int32
dtypes: UInt32(1), datetime64[ns](3), float64(4), int32(2), int64(6), object(10)
memory usage: 21.5+ MB

In [ ]:
pd.set_option('display.max_columns', 25)
olist_df.head(5)

,order_id,order_purchase_timestamp,datetime,diff_days,weekly,product_id,seller_id,price,freight_value,product_category_name,seller_zip_code_prefix,seller_city,...,payment_sequential,payment_type,payment_installments,payment_value,value_log,customer_unique_id,customer_zip_code_prefix,customer_city,review_score,review_creation_date,answer_hour,day_of_month
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2017-10-02 10:56:33,-8,41,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas,9350,maua,...,1,credit_card,1,18.12,2.897016,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,4,2017-10-11,3,11
1,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2017-10-02 10:56:33,-8,41,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas,9350,maua,...,3,voucher,1,2.00,0.693147,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,4,2017-10-11,3,11
2,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2017-10-02 10:56:33,-8,41,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas,9350,maua,...,2,voucher,1,18.59,2.922624,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,4,2017-10-11,3,11
3,128e10d95713541c87cd1a2e48201934,2017-08-15 18:29:31,2017-08-15 18:29:31,-10,33,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,7.78,utilidades_domesticas,9350,maua,...,1,credit_card,3,37.77,3.631515,3a51803cc0d012c3b5dc8b7528cb05f7,3366,sao paulo,4,2017-08-19,15,19
4,0e7e841ddf8f8f2de2bad69267ecfbcf,2017-08-02 18:24:47,2017-08-02 18:24:47,-8,32,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,7.78,utilidades_domesticas,9350,maua,...,1,credit_card,1,37.77,3.631515,ef0996a1a279c26e7ecbd737be23d235,2290,sao paulo,5,2017-08-08,23,8

In [ ]:
# Save dataset with preprocessed data
olist_df.to_pickle('notebooks/datasets/processed_dataset.pkl')